dataset:
  test:
    _base_: cfgs/dataset_configs/ModelNet40.yaml
    others:
      subset: test
  train:
    _base_: cfgs/dataset_configs/ModelNet40.yaml
    others:
      subset: train
  val:
    _base_: cfgs/dataset_configs/ModelNet40.yaml
    others:
      subset: test
grad_norm_clip: 10
max_epoch: 200
model:
  NAME: PointTransformer
  cls_dim: 40
  depth: 12
  drop_path_rate: 0.2
  ema_decay: 0.999
  encoder_dims: 384
  feat_agg: mean_max
  group_size: 32
  head_dp: 0.5
  num_group: 64
  num_heads: 6
  smoothing: 0.0
  trans_dim: 384
  type: mlp3
npoints: 1024
optimizer:
  head:
    lr: 2e-3
    weight_decay: 0.05
  kwargs:
    lr: 1.4e-05
    weight_decay: 0.035
  type: AdamW
scheduler:
  kwargs:
    epochs: 200
    initial_epochs: 10
  type: CosLR
seed: 105
step_per_update: 1
total_bs: 32
